version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: bookroom_nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./public:/var/www/html/public
      - ./views:/var/www/html/views
      - ./src:/var/www/html/src
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - php
    networks:
      - bookroom_network

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: bookroom_php
    volumes:
      - ./public:/var/www/html/public
      - ./views:/var/www/html/views
      - ./src:/var/www/html/src
    networks:
      - bookroom_network

  db:
    image: postgres:15
    container_name: bookroom_db
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: bookroom
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - bookroom_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: bookroom_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bookroom.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - bookroom_network

networks:
  bookroom_network:
    driver: bridge

volumes:
  db_data:
